version: "3.8"
services:
  wcc-distance-calculator:
    container_name: wcc-distance-calculator
    depends_on: [postgres]
    image: "wcc-distance-calculator:1.0.0-SNAPSHOT"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  postgres:
    container_name: postgres-local
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local